export type SeedTopic = {
  title: string;
  description?: string;
  keywords?: string[]; // extra terms used only for auto-link matching, not shown in UI
};

export type SeedArea = {
  title: string;
  description?: string;
  topics: SeedTopic[];
};

export type SeedTrack = {
  title: string;
  description?: string;
  icon: string;
  areas: SeedArea[];
};

export const DEFAULT_CURRICULUM: SeedTrack[] = [
  {
    title: "AI Engineer",
    description: "Production-grade LLM application engineering",
    icon: "🤖",
    areas: [
      {
        title: "Foundations",
        topics: [
          { title: "Transformer architecture overview", keywords: ["Transformer 架构"] },
          { title: "Self-attention mathematical derivation", keywords: ["自注意力", "Self-Attention"] },
          { title: "Multi-Head Attention design rationale", keywords: ["Multi-Head Attention", "MHA"] },
          { title: "MHA / GQA / MQA / MLA comparison", keywords: ["GQA", "MQA", "MLA"] },
          { title: "KV Cache mechanics", keywords: ["KV Cache", "KV 缓存"] },
          { title: "Sliding window / local attention", keywords: ["Sliding Window", "局部注意力"] },
          { title: "Positional encoding: RoPE", keywords: ["RoPE", "位置编码"] },
          { title: "Positional encoding: ALiBi vs RoPE tradeoffs", keywords: ["ALiBi"] },
          { title: "Tokenization: BPE / SentencePiece / Tiktoken", keywords: ["BPE", "Tokenization", "分词"] },
          { title: "Embedding model selection (bge / e5 / OpenAI / Cohere)", keywords: ["Embedding 模型", "bge", "e5"] },
          { title: "Mixture of Experts routing", keywords: ["MoE", "Mixture of Experts", "混合专家"] },
          { title: "Model family comparison (GPT/Claude/Llama/Qwen/DeepSeek)", keywords: ["模型家族", "GPT", "Llama"] },
        ],
      },
      {
        title: "Prompting & Reasoning",
        topics: [
          { title: "Prompt engineering principles", keywords: ["Prompt engineering", "提示词工程"] },
          { title: "System prompt design", keywords: ["system prompt", "System Prompt"] },
          { title: "Few-shot: when and how many", keywords: ["Few-shot", "few shot"] },
          { title: "Chain-of-Thought: triggers and failure modes", keywords: ["CoT", "Chain-of-Thought", "思维链"] },
          { title: "Tree-of-Thoughts applicability", keywords: ["ToT", "Tree-of-Thoughts", "思维树"] },
          { title: "Self-consistency voting", keywords: ["Self-Consistency"] },
          { title: "Self-reflection / self-critique in production", keywords: ["Self-Reflection", "Self-Critique", "反思"] },
          { title: "Structured output: JSON mode / schema-guided", keywords: ["JSON mode", "Structured Output", "结构化输出"] },
          { title: "Constitutional AI", keywords: ["Constitutional AI", "对齐"] },
          { title: "Prompt template management and versioning", keywords: ["Prompt 管理", "prompt template"] },
        ],
      },
      {
        title: "RAG Systems",
        topics: [
          { title: "RAG end-to-end data flow", keywords: ["RAG 系统", "RAG 数据流", "RAG 整体"] },
          { title: "Chunking: fixed / semantic / parent-child", keywords: ["Chunking", "切分", "切片"] },
          { title: "Chunking: code / tables / markdown special cases", keywords: ["代码切分", "表格切分"] },
          { title: "Dense retrieval fundamentals", keywords: ["dense retrieval", "稠密检索", "向量检索"] },
          { title: "Sparse retrieval (BM25 / SPLADE)", keywords: ["BM25", "SPLADE", "稀疏检索"] },
          { title: "Hybrid search fusion (RRF / weighted)", keywords: ["Hybrid Search", "混合检索", "RRF"] },
          { title: "Reranking model selection and timing", keywords: ["Reranking", "Reranker", "重排"] },
          { title: "Cross-encoder vs Bi-encoder", keywords: ["Cross-encoder", "Bi-encoder", "双塔"] },
          { title: "Query rewriting / decomposition", keywords: ["Query Rewriting", "查询改写"] },
          { title: "HyDE / step-back prompting", keywords: ["HyDE", "Step-back"] },
          { title: "Long-context vs RAG tradeoffs", keywords: ["Long-context", "长上下文"] },
          { title: "Contextual retrieval (Anthropic approach)", keywords: ["Contextual Retrieval"] },
          { title: "Graph RAG applicability", keywords: ["Graph RAG", "知识图谱"] },
          { title: "RAG eval: faithfulness / answer relevance / context precision", keywords: ["RAG eval", "RAG 评估", "Evals"] },
          { title: "Multi-modal RAG (images / PDFs)", keywords: ["multi-modal RAG", "多模态 RAG"] },
        ],
      },
      {
        title: "Agents",
        topics: [
          { title: "ReAct pattern", keywords: ["ReAct"] },
          { title: "Plan-and-Execute pattern", keywords: ["Plan-Execute", "Plan and Execute"] },
          { title: "Multi-Agent collaboration architecture", keywords: ["Multi-Agent", "多智能体"] },
          { title: "Tool use interface design (OpenAI / Anthropic schemas)", keywords: ["Tool Use", "工具调用", "Function Calling"] },
          { title: "Function calling failure modes", keywords: ["Function Calling 失败"] },
          { title: "Agent routing / decision-making", keywords: ["Agent 路由", "Agent 决策"] },
          { title: "Short-term memory (conversation buffer)", keywords: ["short-term memory", "对话记忆"] },
          { title: "Long-term memory (vector store)", keywords: ["long-term memory", "长期记忆"] },
          { title: "Episodic / procedural memory concepts", keywords: ["Episodic Memory", "情景记忆"] },
          { title: "Agent state management (state machines)", keywords: ["Agent 状态机"] },
          { title: "Computer Use / Browser Use deployment", keywords: ["Computer Use", "Browser Use"] },
          { title: "Agent eval (task success / efficiency)", keywords: ["Agent eval", "Agent 评估"] },
          { title: "Subagent orchestration (Claude Code pattern)", keywords: ["Subagent", "子代理"] },
        ],
      },
      {
        title: "Vector DB & Retrieval Infra",
        topics: [
          { title: "Vector DB comparison (Milvus/Qdrant/Pinecone/pgvector/Weaviate)", keywords: ["Milvus", "Qdrant", "Pinecone", "pgvector", "向量数据库"] },
          { title: "HNSW index internals", keywords: ["HNSW"] },
          { title: "IVF / IVF-PQ index internals", keywords: ["IVF"] },
          { title: "Quantized indexes (PQ / SQ)", keywords: ["PQ 量化", "向量量化"] },
          { title: "Filtering with vectors (pre vs post)", keywords: ["pre filter", "post filter"] },
          { title: "Vector dimensionality choice (768 / 1024 / 1536)", keywords: ["向量维度"] },
          { title: "Multi-vector retrieval (ColBERT-style)", keywords: ["ColBERT"] },
          { title: "Build-time vs query-time tradeoffs", keywords: ["索引构建"] },
          { title: "Vector store HA design", keywords: ["向量库高可用"] },
          { title: "Hybrid index architecture (Milvus + ES)", keywords: ["混合索引"] },
        ],
      },
      {
        title: "Production LLM Engineering",
        topics: [
          { title: "Streaming / SSE implementation", keywords: ["Streaming", "SSE", "流式"] },
          { title: "Rate limit / 429 / exponential backoff", keywords: ["rate limit", "429", "限流", "重试"] },
          { title: "Provider failover / multi-provider routing", keywords: ["Provider failover", "多 provider"] },
          { title: "Prompt cache mechanics (Anthropic / OpenAI)", keywords: ["Prompt cache", "提示缓存"] },
          { title: "KV cache reuse", keywords: ["KV cache 复用"] },
          { title: "Semantic cache design", keywords: ["semantic cache", "语义缓存"] },
          { title: "Cost tracking and attribution", keywords: ["cost", "成本"] },
          { title: "Token budget control", keywords: ["token 预算", "token budget"] },
          { title: "Observability: trace / log / metric", keywords: ["observability", "可观测", "trace"] },
          { title: "Evals engineering (offline / online)", keywords: ["Evals", "LLM 评估"] },
          { title: "Prompt injection attack vectors", keywords: ["Prompt Injection 攻击"] },
          { title: "Prompt injection defense strategies", keywords: ["Prompt Injection 防御"] },
          { title: "Hallucination causes and mitigations", keywords: ["幻觉", "hallucination"] },
        ],
      },
      {
        title: "Fine-tuning & Post-training",
        topics: [
          { title: "When to fine-tune (vs RAG / prompting)", keywords: ["fine-tune", "微调"] },
          { title: "SFT data preparation", keywords: ["SFT"] },
          { title: "DPO theory and applicability", keywords: ["DPO"] },
          { title: "RLHF pipeline", keywords: ["RLHF"] },
          { title: "GRPO (DeepSeek-R1 method)", keywords: ["GRPO", "DeepSeek-R1"] },
          { title: "LoRA mathematical foundations", keywords: ["LoRA"] },
          { title: "QLoRA quantized training", keywords: ["QLoRA"] },
          { title: "Distillation pipeline", keywords: ["Distillation", "蒸馏"] },
          { title: "Catastrophic forgetting mitigation", keywords: ["Catastrophic forgetting", "灾难性遗忘"] },
          { title: "Continued pretraining: when to use", keywords: ["Continued pretraining", "持续预训练"] },
        ],
      },
      {
        title: "Inference & Deployment",
        topics: [
          { title: "vLLM architecture and PagedAttention", keywords: ["vLLM", "PagedAttention"] },
          { title: "SGLang vs vLLM", keywords: ["SGLang"] },
          { title: "TensorRT-LLM applicability", keywords: ["TensorRT"] },
          { title: "INT8 / INT4 quantization fundamentals", keywords: ["INT8 量化", "INT4 量化"] },
          { title: "AWQ vs GPTQ", keywords: ["AWQ", "GPTQ"] },
          { title: "Speculative decoding", keywords: ["Speculative decoding", "投机解码"] },
          { title: "Continuous batching", keywords: ["Continuous batching"] },
          { title: "Edge inference: GGUF / Ollama", keywords: ["GGUF", "Ollama"] },
          { title: "llama.cpp deployment", keywords: ["llama.cpp"] },
          { title: "Inference cost estimation", keywords: ["推理成本"] },
        ],
      },
      {
        title: "Multimodal",
        topics: [
          { title: "VLM architectures (CLIP / LLaVA)", keywords: ["VLM", "CLIP", "LLaVA"] },
          { title: "Vision encoder selection", keywords: ["视觉编码器"] },
          { title: "Document understanding (OCR + layout)", keywords: ["OCR", "文档理解"] },
          { title: "TTS model selection (ElevenLabs / Azure / OSS)", keywords: ["TTS", "语音合成"] },
          { title: "ASR model selection (Whisper / Deepgram)", keywords: ["ASR", "Whisper", "语音识别"] },
          { title: "Image generation pipelines (SD / Flux)", keywords: ["Stable Diffusion", "Flux", "图像生成"] },
          { title: "Video understanding", keywords: ["视频理解"] },
          { title: "Multi-modal RAG", keywords: ["多模态"] },
        ],
      },
    ],
  },
  {
    title: "Backend Architect",
    description: "Distributed systems and high-scale backend architecture",
    icon: "🏗️",
    areas: [
      {
        title: "Computer Fundamentals",
        topics: [
          { title: "Linux processes / threads / coroutines", keywords: ["Linux 进程", "Linux 线程"] },
          { title: "Linux memory management", keywords: ["Linux 内存管理"] },
          { title: "Linux IO multiplexing (select/poll/epoll)", keywords: ["IO 多路复用", "epoll", "select"] },
          { title: "Linux signals / graceful shutdown", keywords: ["Linux 信号", "优雅停机"] },
          { title: "Linux boot / systemd basics", keywords: ["Linux 启动", "systemd"] },
          { title: "Performance: top / pidstat / perf / pmap", keywords: ["top", "pidstat", "perf", "pmap"] },
          { title: "Performance: vmstat / iostat / sar / eBPF", keywords: ["vmstat", "iostat", "sar", "eBPF"] },
          { title: "TCP handshake / state machine", keywords: ["TCP 三次握手", "TCP 状态"] },
          { title: "HTTP/2 multiplexing", keywords: ["HTTP/2", "HTTP 2"] },
          { title: "HTTP/3 / QUIC design rationale", keywords: ["HTTP/3", "QUIC"] },
        ],
      },
      {
        title: "Programming Languages",
        topics: [
          { title: "Go GMP scheduler", keywords: ["GMP", "Go 调度"] },
          { title: "Go GC tri-color marking", keywords: ["Go GC", "三色标记"] },
          { title: "Go memory escape analysis", keywords: ["Go 内存逃逸", "逃逸分析"] },
          { title: "Go channel internals", keywords: ["Go Channel"] },
          { title: "Go slice internals", keywords: ["Go Slice"] },
          { title: "Go map internals / sync.Map", keywords: ["Go Map", "sync.Map"] },
          { title: "Go interface internals (iface / eface)", keywords: ["Go interface", "iface", "eface"] },
          { title: "Go defer mechanics", keywords: ["Go defer"] },
          { title: "Go context cancellation", keywords: ["Go Context"] },
          { title: "Go concurrency pitfalls", keywords: ["Go 并发陷阱"] },
          { title: "Go memory model / happens-before", keywords: ["Go 内存模型", "happens-before"] },
          { title: "Go pprof in practice", keywords: ["Go pprof"] },
          { title: "Go reflection performance", keywords: ["Go 反射"] },
          { title: "Rust ownership / borrowing", keywords: ["Rust 所有权"] },
          { title: "Rust async / tokio model", keywords: ["Rust async", "tokio"] },
        ],
      },
      {
        title: "Databases",
        topics: [
          { title: "MySQL B+ tree indexes", keywords: ["MySQL 索引", "B+ 树"] },
          { title: "MySQL transaction isolation levels", keywords: ["MySQL 事务隔离"] },
          { title: "MySQL locking mechanics", keywords: ["MySQL 锁", "Next-Key Lock", "间隙锁"] },
          { title: "MySQL MVCC", keywords: ["MVCC"] },
          { title: "MySQL master-slave replication", keywords: ["MySQL 主从", "主从复制"] },
          { title: "Redo log / Undo log / Binlog", keywords: ["Redo log", "Undo log", "Binlog"] },
          { title: "SQL slow query diagnosis", keywords: ["慢查询", "SQL 慢"] },
          { title: "MySQL vs PostgreSQL selection", keywords: ["MySQL 和 PostgreSQL", "PostgreSQL"] },
          { title: "Sharding strategies", keywords: ["分库分表"] },
          { title: "Distributed ID generation", keywords: ["分布式 ID"] },
          { title: "Read-write splitting", keywords: ["读写分离"] },
          { title: "NewSQL (TiDB / CockroachDB)", keywords: ["TiDB", "CockroachDB", "NewSQL"] },
          { title: "Time-series DBs (InfluxDB / TimescaleDB)", keywords: ["InfluxDB", "时序数据库"] },
          { title: "Graph DBs (Neo4j / NebulaGraph)", keywords: ["Neo4j", "图数据库"] },
          { title: "OLAP engines (ClickHouse / Doris)", keywords: ["ClickHouse", "Doris", "OLAP"] },
        ],
      },
      {
        title: "Redis & Caching",
        topics: [
          { title: "Why Redis is fast", keywords: ["Redis 为什么快"] },
          { title: "Redis 6 multi-threading", keywords: ["Redis 6", "Redis 多线程"] },
          { title: "Redis persistence: RDB vs AOF", keywords: ["RDB", "AOF", "Redis 持久化"] },
          { title: "Redis replication / sentinel / cluster", keywords: ["Redis 主从", "哨兵", "Redis 集群"] },
          { title: "Redis eviction policies", keywords: ["Redis 内存", "淘汰策略"] },
          { title: "Redis distributed lock / Redlock", keywords: ["Redis 分布式锁", "Redlock"] },
          { title: "Redis hot keys / large keys", keywords: ["Redis 热点 key", "大 key"] },
          { title: "Cache penetration / breakdown / avalanche", keywords: ["缓存穿透", "缓存击穿", "缓存雪崩"] },
          { title: "Cache consistency patterns (Cache Aside / Write Through)", keywords: ["Cache Aside", "缓存一致性"] },
          { title: "Multi-tier cache design", keywords: ["多级缓存"] },
          { title: "Local cache (Caffeine / freecache)", keywords: ["Caffeine", "本地缓存"] },
          { title: "Redis Stream / Pub-Sub", keywords: ["Redis Stream", "Redis Pub"] },
        ],
      },
      {
        title: "Message Queues",
        topics: [
          { title: "Why Kafka is fast", keywords: ["Kafka 为什么快"] },
          { title: "Kafka rebalance", keywords: ["Kafka Rebalance"] },
          { title: "Kafka vs RabbitMQ selection", keywords: ["Kafka 和 RabbitMQ", "RabbitMQ"] },
          { title: "Kafka replication / ISR", keywords: ["Kafka 副本", "ISR"] },
          { title: "Kafka exactly-once semantics", keywords: ["Exactly Once"] },
          { title: "RabbitMQ model", keywords: ["RabbitMQ 模型"] },
          { title: "Pulsar architecture / compute-storage separation", keywords: ["Pulsar"] },
          { title: "Idempotent message design", keywords: ["消息幂等", "幂等"] },
          { title: "Message ordering guarantees", keywords: ["消息顺序"] },
          { title: "Dead letter / delay queues", keywords: ["死信队列", "延迟队列"] },
        ],
      },
      {
        title: "Microservices",
        topics: [
          { title: "Service decomposition principles (DDD)", keywords: ["DDD", "服务拆分"] },
          { title: "Service discovery / registry (Nacos/Consul/Eureka)", keywords: ["服务发现", "Nacos", "Consul"] },
          { title: "API Gateway pattern", keywords: ["API Gateway", "网关"] },
          { title: "BFF pattern", keywords: ["BFF"] },
          { title: "Circuit breaker (Hystrix / Sentinel)", keywords: ["熔断", "Hystrix", "Sentinel"] },
          { title: "Rate limiting (token bucket / leaky bucket / sliding window)", keywords: ["限流算法", "令牌桶", "漏桶"] },
          { title: "Degradation strategy", keywords: ["降级"] },
          { title: "Distributed tracing (Jaeger / SkyWalking)", keywords: ["链路追踪", "Jaeger", "SkyWalking"] },
          { title: "Config center (Apollo / Nacos)", keywords: ["配置中心", "Apollo"] },
          { title: "gRPC fundamentals and usage", keywords: ["gRPC"] },
          { title: "Service Mesh (Istio / Linkerd)", keywords: ["Service Mesh", "Istio"] },
          { title: "Canary / blue-green deployment", keywords: ["灰度发布", "蓝绿部署"] },
          { title: "Cell architecture", keywords: ["单元化"] },
        ],
      },
      {
        title: "Distributed Systems",
        topics: [
          { title: "CAP / BASE tradeoffs", keywords: ["CAP", "BASE"] },
          { title: "Paxos / Raft consensus", keywords: ["Paxos", "Raft", "共识"] },
          { title: "Distributed transactions: 2PC / 3PC", keywords: ["2PC", "3PC"] },
          { title: "Distributed transactions: TCC", keywords: ["TCC"] },
          { title: "Distributed transactions: Saga", keywords: ["Saga"] },
          { title: "Distributed transactions: local message table", keywords: ["本地消息表"] },
          { title: "Consistent hashing", keywords: ["一致性哈希"] },
          { title: "Distributed lock implementations", keywords: ["分布式锁"] },
          { title: "Distributed ID (Snowflake / UUID / segment)", keywords: ["雪花", "Snowflake", "号段"] },
          { title: "Idempotency design patterns", keywords: ["幂等设计"] },
          { title: "Global clocks (TrueTime / HLC)", keywords: ["TrueTime", "HLC"] },
          { title: "Split-brain problem", keywords: ["脑裂"] },
          { title: "Quorum mechanisms", keywords: ["Quorum"] },
        ],
      },
      {
        title: "High-Concurrency Design",
        topics: [
          { title: "Rate limit algorithm implementations", keywords: ["限流实现"] },
          { title: "IM system design", keywords: ["IM 即时通讯", "IM 系统"] },
          { title: "Feed: push / pull / hybrid", keywords: ["Feed 流", "推拉结合"] },
          { title: "Feed: celebrity-with-millions-of-followers problem", keywords: ["大 V"] },
          { title: "Flash sale system", keywords: ["秒杀"] },
          { title: "URL shortener design", keywords: ["短链"] },
          { title: "Leaderboard system design", keywords: ["排行榜"] },
          { title: "Comment system design", keywords: ["评论系统"] },
          { title: "Like / vote system design", keywords: ["点赞"] },
          { title: "Red packet system design", keywords: ["红包"] },
          { title: "Online / offline presence system", keywords: ["在线状态"] },
          { title: "Notification / push system", keywords: ["通知推送"] },
          { title: "Search system design", keywords: ["搜索系统"] },
        ],
      },
      {
        title: "Containers & Cloud Native",
        topics: [
          { title: "Docker image layers", keywords: ["Docker 镜像", "镜像分层"] },
          { title: "Dockerfile best practices", keywords: ["Dockerfile"] },
          { title: "Docker network modes", keywords: ["Docker 网络"] },
          { title: "K8s overall architecture", keywords: ["K8s 架构", "K8s 整体"] },
          { title: "K8s Pod / workload controllers", keywords: ["K8s Pod", "Deployment", "StatefulSet"] },
          { title: "K8s Service / Ingress", keywords: ["K8s Service", "Ingress"] },
          { title: "K8s scheduling", keywords: ["K8s 调度", "affinity"] },
          { title: "K8s ConfigMap / Volume", keywords: ["ConfigMap", "Volume", "PVC"] },
          { title: "K8s health checks / HPA", keywords: ["K8s 健康检查", "HPA"] },
          { title: "Operator pattern / CRD", keywords: ["Operator", "CRD"] },
        ],
      },
      {
        title: "Observability",
        topics: [
          { title: "Logging / metrics / tracing pillars", keywords: ["三大支柱", "三支柱"] },
          { title: "Prometheus data model", keywords: ["Prometheus"] },
          { title: "Grafana dashboard design", keywords: ["Grafana"] },
          { title: "OpenTelemetry standard", keywords: ["OpenTelemetry", "OTel"] },
          { title: "Structured logging and collection (ELK / Loki)", keywords: ["ELK", "Loki", "结构化日志"] },
          { title: "APM tool comparison", keywords: ["APM"] },
          { title: "SLI / SLO / SLA system", keywords: ["SLO", "SLI", "SLA"] },
          { title: "Alert design principles", keywords: ["告警"] },
        ],
      },
      {
        title: "Security",
        topics: [
          { title: "OAuth2 flows", keywords: ["OAuth2", "OAuth"] },
          { title: "JWT design and pitfalls", keywords: ["JWT"] },
          { title: "SSO implementation", keywords: ["SSO"] },
          { title: "TLS / mTLS", keywords: ["TLS", "mTLS"] },
          { title: "Symmetric / asymmetric encryption", keywords: ["对称加密", "非对称加密"] },
          { title: "Key management / KMS", keywords: ["KMS", "密钥管理"] },
          { title: "XSS / CSRF / SQL injection defense", keywords: ["XSS", "CSRF", "SQL 注入"] },
          { title: "DDoS defense", keywords: ["DDoS"] },
          { title: "Authorization (horizontal / vertical)", keywords: ["越权"] },
          { title: "Audit logs", keywords: ["审计日志"] },
        ],
      },
      {
        title: "Algorithms (Systems-Relevant)",
        topics: [
          { title: "LRU implementation", keywords: ["LRU"] },
          { title: "LFU implementation", keywords: ["LFU"] },
          { title: "Top K problem", keywords: ["Top K"] },
          { title: "Bloom filter", keywords: ["布隆过滤器", "Bloom"] },
          { title: "HyperLogLog", keywords: ["HyperLogLog"] },
          { title: "Count-Min Sketch", keywords: ["Count-Min Sketch"] },
          { title: "Skip list", keywords: ["跳表", "Skip List"] },
          { title: "Consistent hashing implementation", keywords: ["一致性哈希实现"] },
        ],
      },
    ],
  },
];
